questions =  [
    {"id": 0, "question": "Svoboda podnikání je nejpraktičtější způsob jak může lidská společnost prosperovat.", "effects": {"right": 1}},
    {"id": 1, "question": "Charita je lepší způsob pomáhání slabším než sociální zabezpečení.", "effects": {"right": 1}},
    {"id": 2, "question": "Mzdy jsou vždy spravedlivé, neboť zaměstnavatel ví moc dobře kolik peněz si jeho pracovník zaslouží.", "effects": {"right": 1}},
    {"id": 3, "question": "Chamtivost je „přirozená lidská povaha“.", "effects": {"right": 1}},
    {"id": 4, "question": "„Vykořisťování“ je zastaralý pojem, protože mezery v kapitalismu 19. století již nejsou.", "effects": {"right": 1}},
    {"id": 5, "question": "Komunismus je vzor, který v praxi nemůže nikdy fungovat.", "effects": {"right": 1}},
    {"id": 6, "question": "Danění bohatých je špatná idea a společnost by se bez něho obešla.", "effects": {"right": 1}},
    {"id": 7, "question": "Čím víc pracuješ, tím víc postupuješ ve společenském žebříčku.", "effects": {"right": 1}},
    {"id": 8, "question": "Organizacím a korporacím se nedá věřit a musejí být regulovány vládou.", "effects": {"right": -1}},
    {"id": 9, "question": "Vláda, která poskytuje každému je neodmyslitelně dobrý nápad.", "effects": {"right": -1}},
    {"id": 10, "question": "Aktuální systém sociálního zabezpečení by měl být nadále rozšířen k boji proti nerovnoprávnosti.", "effects": {"right": -1}},
    {"id": 11, "question": "Něčí půda není komoditou, která by měla být k prodeji či naprodej..", "effects": {"right": -1}},
    {"id": 12, "question": "Veškerý průmysl a všechny banky by měly být znárodněny.", "effects": {"right": -1}},
    {"id": 13, "question": "Třída je základní dělení lidské společnosti.", "effects": {"right": -1}},
    {"id": 14, "question": "Ve světe je ekonomická nerovnost příliš vysoká.", "effects": {"right": -1}},
    {"id": 15, "question": "Občas je v pořádku když vláda špehuje své občany v zájmu boje proti extrémistům a teroristům.", "effects": {"auth": 1}},
    {"id": 16, "question": "Morálně korektní autoritní figury jsou dobrou věcí pro lid.", "effects": {"auth": 1}},
    {"id": 17, "question": "Pro úspěch každé vlády je potřebná síla.", "effects": {"auth": 1}},
    {"id": 18, "question": "Pouze vláda dokáže férově a efektivně regulovat organizace.", "effects": {"auth": 1}},
    {"id": 19, "question": "Lidská společnost potřebuje nějakou strukturu a byrokracii, aby funovala.", "effects": {"auth": 1}},
    {"id": 20, "question": "V zájmu veřejné bezpečnosti by měly být zavedeny povinné průkazy totožnosti.", "effects": {"auth": 1}},
    {"id": 21, "question": "V dobách krize je bezpečnost důležitější než občanské svobody.", "effects": {"auth": 1}},
    {"id": 22, "question": "Pokud nemáš co skrývat, nemáš se čeho obávat.", "effects": {"auth": 1}},
    {"id": 23, "question": "Vláda by se měla co nejmíň zapojovat do každodenních životů svých občanů.", "effects": {"auth": -1}},
    {"id": 24, "question": "Bez demokracie není společnost ničím.", "effects": {"auth": -1}},
    {"id": 25, "question": "Zrušení poroty by mělo být legální.", "effects": {"auth": -1}},
    {"id": 26, "question": "Čím menší vláda, tím svobodnější lidé.", "effects": {"auth": -1}},
    {"id": 27, "question": "Vláda by měla maximálně poskytovat jen pohotovostní služby a vynucení zákona.", "effects": {"auth": -1}},
    {"id": 28, "question": "Policie nebyla založena k ochraně lidí, ale k vynucení status quo silou.", "effects": {"auth": -1}},
    {"id": 29, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "Dva souhlasní jedinci mají právo si s každým dělat co chtěji i když je mi to nepříjmené.", "effects": {"prog": 1}},
    {"id": 31, "question": "Tělo jedince je jeho vlastní majetek a má právo s ním dělat co jenom chce.", "effects": {"prog": 1}},
    {"id": 32, "question": "Člověk by měl mít právo uctívat kohokoli a cokoli chce.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudismus je dokonale přirozený.", "effects": {"prog": 1}},
    {"id": 34, "question": "Zvířata si slouží nějaká univezální práva.", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender je pouze sociální konstrukt, ne přirozeným stavem jedinců.", "effects": {"prog": 1}},
    {"id": 36, "question": "Zákony založené na kulturních hodnotách, namísto na těch etických nejsou spravedlivé.", "effects": {"prog": 1}},
    {"id": 37, "question": "Tělesná autonomie se týká i nezletilých, psychicky postižené i vážné zločince.", "effects": {"prog": 1}},
    {"id": 38, "question": "Homosexualita je proti mým hodnotám.", "effects": {"prog": -1}},
    {"id": 39, "question": "Transsexuálové by neměli mít právo si adoptovat dítě.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drogy jsou škodlivé a měly by být zakázány.", "effects": {"prog": -1}},
    {"id": 41, "question": "Trest smrti by měl u určitých zločinů pořád existovat.", "effects": {"prog": -1}},
    {"id": 42, "question": "Bezobětné zločiny by měly být stále trestány.", "effects": {"prog": -1}},
    {"id": 43, "question": "Bez duchovního vyznání nelze být morální.", "effects": {"prog": -1}},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}}
];
